apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

commonAnnotations:
    argocd-image-updater.argoproj.io/image-list: nitish9282/nginx:1.x
    argocd-image-updater.argoproj.io/write-back-method: git

namePrefix: nitishv-

patches:
        - patch: |-
                - op: add
                  path: "/spec/ports/0/nodePort"
                  value: 31189
                - op: add
                  path: "/spec/type"
                  value: "NodePort"
          target:
            kind: Service
            name: "guestbook-ui"     
images:
  - name: nginx
    newName: nitish9282/nginx
    newTag: v2

