apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

namePrefix: nitish-

patches:
        - patch: |-
                - op: add
                  path: "/spec/ports/0/nodePort"
                  value: 31189
                - op: add
                  path: "/spec/type"
                  value: "NodePort"
          target:
            kind: Service
            name: "guestbook-ui"            

